version: 1
accounts:
  - name: alice
    coins: ["2000000000token", "200000000stake"]
  - name: bob
    coins: ["10000token", "100000000stake"]
  - name: tom
    coins: ["1000000token"]
  - name: jerry
    coins: ["10token"]
validators:
  - name: alice
    bonded: "100000000token"
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
genesis:
  app_state:
    staking:
      params:
        bond_denom: "token"